### ISSUE TITLE
Road to v1.0

### ISSUE THREAD

**Issue by Gabriel-p** [Gabriel-p/photpy#14]
List of issues to close before 1.0 can be published:

- [ ] Get rid of `psfmeasure` in `fitstats` script #17
- [x] Extract the crop process from `align_crop` and deprecate the alignment #20
- [x] Extract a more general `pymatch` process from `id_standard` #19
- [ ] Add flip support to pymatch script #6
- [x] Limit the number of stars used in pymatch script #8
- [ ] Solve transformation equations #7
- [ ] Assign errors to aperture photometry values #16 
- [ ] Perform linear regression taking errors in x,y into account in `fit_standards` script #10
- [ ] Finish `psf_phot` script #18
- [ ] Duplicate DAOMASTER's main functions #12 

Two good resources ([source](https://www.facebook.com/groups/astropython/permalink/2240620399515971/)):
> The 2017 and 2018 versions of my lecture notes are here:
2017: https://ysbach.github.io/AO_2017/
2018: https://ysbach.github.io/AO_LectureNotes/
