### ISSUE TITLE
Extract a more general 'match' process from id_standard

### ISSUE THREAD

**Issue by Gabriel-p** [Gabriel-p/photpy#19]
This script should act as as replacement to the (DAO)MATCH code.

- [ ] Add flip support #6
- [x] Limit the number of stars used #8 
- [ ] Solve transformation equations #7
- [x] Accept any number of frames, not just a standard frame. Align these to a given reference frame.
- [ ] Output transformation values to file (to be used by `match_transf` as done by DAOMASTER to refine the matching)

**Comment by Gabriel-p** [comment]
This turned out to be a **much** more difficult issue than anticipated. Standard frames come in a lot of different sizes and it is really hard to produce a good match. Things I've tried:

1. Full auto: let the script find sources in the *entire* observed frame, and select the N brightest. Auto match by the method of matching triangles (MMT).
2. Semi auto: let the script find sources in *a region* of the observed frame, and select the N brightest. Perform MMT.
3. Manual with no ID: select as many as possible reference stars in the observed frame *manually*  without telling the script which is which. Perform MMT.

None of the above worked in general. Finally I resorted to:

4. Manual with ID: select three reference stars (covering as much of the reference frame as possible) and provide also their IDs. Then obtain scale, rotation, and translation directly with no MMT.
